### ISSUE TITLE
looks like you forgot to add Recipies folder which was in your home directory

### ISSUE THREAD

**Issue by redoC-A2k** [szymciolop/RecipeManager#1]
Error opening directory “/home/afshan/Recipes/”: No such file or directory (g-file-error-quark, 4)
zsh: segmentation fault (core dumped)  ./recipe

I am getting this error on running ./recipe 
(/home/afshan is my home directory)

**Comment by szymonlopaciuk** [comment]
You're right! Seems like I forgot to actually create the folder in https://github.com/szymonlopaciuk/RecipeManager/blob/master/src/application.vala#L26. I will try to fix this tonight.

Honestly this project is so old I am surprised it still even builds! It's nice to know somebody did (:

**Comment by redoC-A2k** [comment]
It would be great if you could fix this ASAP , I was going through some gtk projects for my college assignment !

**Comment by szymonlopaciuk** [comment]
It's not the world's best fix but it will do. If you need some sample recipe files, they can be found in my other repo https://github.com/szymonlopaciuk/recipes,

I noticed on my current machine the install script is a bit buggy, and when run with `sudo` (as it should be, as it install the binary to `/usr/bin`) it tries to install the config files for the user `root` instead of the local user. The workaround is to run the install script specifying $HOME manually, like so:

```sh
sudo HOME=/home/username make install
```
This app is far from perfect, an old project of mine, and so you need to actually run this for the app to run as it installs the right config file. If you don't want to do that, feel free to just move the config file in this repo to `~/.config` and that should do the trick too.
